name = "notion-ics"
compatibility_date = "2025-01-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_flags = ["nodejs_compat"]

[vars]
NOTION_TOKEN = "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"
ACCESS_KEY = "3dw9UjWPyllrGEsSfWXtvyGMpHFZydKgI0vPRCHRdWOY4yBkm4OsY0twFbsFxeD4"
EMAIL_USER = "support@smtp.ari-integration.com"
EMAIL_PASS =  "726107dfbc8295090f453e0f"
EMAIL_TO =  "michal@ferber.me"
